export enum TerminalColors {
	Reset = '\x1b[0m',
	Bright = '\x1b[1m',
	Dim = '\x1b[2m',
	Underscore = '\x1b[4m',
	Blink = '\x1b[5m',
	Reverse = '\x1b[7m',
	Hidden = '\x1b[8m',
	FontBlack = '\x1b[30m',
	FontRed = '\x1b[31m',
	FontGreen = '\x1b[32m',
	FontYellow = '\x1b[33m',
	FontBlue = '\x1b[34m',
	FontMagenta = '\x1b[35m',
	FontCyan = '\x1b[36m',
	FontWhite = '\x1b[37m',
	BackgroundBlack = '\x1b[40m',
	BackgroundRed = '\x1b[41m',
	BackgroundGreen = '\x1b[42m',
	BackgroundYellow = '\x1b[43m',
	BackgroundBlue = '\x1b[44m',
	BackgroundMagenta = '\x1b[45m',
	BackgroundCyan = '\x1b[46m',
	BackgroundWhite = '\x1b[47m',
}
